
baseurl: "" # the subpath of your site, e.g. /blog

permalink: /blog/:slug/

plugins:
  - jekyll-last-modified-at
  - jekyll-scholar
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------
title: Your Name # the name of your site, e.g. ACME Corp.

tagline: A text-focused Jekyll theme # it will display as the subtitle

description: A minimal, responsive and feature-rich Jekyll theme for technical writing.

url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com

# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# ↑ --------------------------

collections:
  pages:
    output: true
  news:
    output: true
    permalink: /news/:slug/
  research:
    output: true


footer:
  show_last_update: true

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

scholar:
  bibliography: references.bib
  style: apa
  bibliography_template: bib
  bibliography_list_tag: ul
  sort_by: year
  order: descending

exclude:
  - README.md
  - CONTRIBUTING.md
  - CONTRIBUTE.md
  - DESIGN.md
  - SUPPORT.md
  - SECURITY.md
  - tailwind_enabler.css
  - CHANGELOG.md
  - "*.gem"
  - "*.gemspec"
  - docs
  - LICENSE
  - "*.config.js"
  - "package*.json"
  - assets/css/merida.src.css
