name: Sync starter repo

on:
  push:
    branches:
      - main
jobs:
  move-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout jekyll-theme-merida repo
        uses: actions/checkout@v6
        with:
          path: theme

      - name: Checkout merida-starter repo
        uses: actions/checkout@v6
        with:
          repository: j0m0k0/merida-starter
          path: starter
          token: ${{ secrets.MERIDA_STARTER_SYNC_TOKEN }}

      - name: Copy selected files to starter
        run: |
          cp -r theme/_bibliography starter/_bibliography
          cp -r theme/_data starter/_data
          cp -r theme/_includes starter/_includes
          cp -r theme/_layouts starter/_layouts
          cp -r theme/_news starter/_news
          cp -r theme/_pages starter/_pages
          cp -r theme/_plugins starter/_plugins
          cp -r theme/_posts starter/_posts
          cp -r theme/assets starter/assets
          cp -r theme/downloads starter/downloads
          cp theme/_config.yml starter/_config.yml

      - name: Create the Gemfile for starter
        run: |
          cat > starter/Gemfile.new <<'EOF'
          # frozen_string_literal: true
          source "https://rubygems.org"

          gem "jekyll-theme-merida", "~> 0.0"
          EOF

          mv starter/Gemfile.new starter/Gemfile
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.MERIDA_STARTER_SYNC_TOKEN }}
          path: starter
          branch: sync-from-theme
          commit-message: Sync merida-starter files from jekyll-theme-merida
          title: Sync merida-starter files from jekyll-theme-merida
          body: |
            This PR syncs starter files from the jekyll-theme-merida repository.
          base: main

